name: Test

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  publish:
    env:
      CI: true
      NODE_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14' ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm ci
      
      - name: Lint Code Base
        uses: github/super-linter@v3.15.5
        env:
          LINTER_RULES_PATH: /
          LOG_LEVEL: 'WARN'
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_STANDARD: false
          DEFAULT_BRANCH: main

      - name: Test
        run: npm test
